---
- name: "=========== Install Docker on Ubuntus ==========="
  hosts: webserver02
  become: true
  tasks:
    - name: "=========== Install dependenciess ==========="
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: "=========== Create directory for apt keyrings ==========="
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: "=========== Download and add Docker GPG keys ==========="
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: "=========== Convert and install Docker GPG keys ==========="
      ansible.builtin.shell:
        cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /tmp/docker.gpg
        creates: /etc/apt/keyrings/docker.gpg

    - name: "=========== Set correct permissions on Docker GPG keys ==========="
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: "=========== Clean up temporary key files ==========="
      ansible.builtin.file:
        path: /tmp/docker.gpg
        state: absent

    - name: "=========== Create Docker APT repository files ==========="
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/docker.list
        content: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        mode: '0644'

    - name: "=========== Update apt package caches ==========="
      ansible.builtin.apt:
        update_cache: true

    - name: Install Docker Engines ==========="
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      state: present

    - name: "=========== Ensure Docker service is running and enableds ==========="
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: "=========== Add current user to docker group (optional)s ==========="
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
