---
- name: "=========== Install Docker on Ubuntu ==========="
  hosts: webserver
  become: true

  tasks:
    - name: "=========== Update apt package index and install prerequisites ==========="
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: present
        #update_cache: true

    - name: "=========== Create directory for apt keyrings ==========="
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Convert Docker GPG key to binary format
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/docker.gpg /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: "=========== Add Docker repository ==========="
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: "=========== Install Docker Engine ==========="
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: "=========== Add current user to docker group ==========="
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
        create_home: false  # Important pour éviter une erreur si l'utilisateur existe déjà

    - name: "=========== Ensure docker service is started and enabled ==========="
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true


- name: "====================== Docker build and push ======================"
  hosts: webserver  # Replace with the hostname or IP address of your target server

  tasks:
    - name: "=========== Stop the container if it's running ==========="
      ansible.builtin.command: docker stop petstore-container-1
      ignore_errors: true

    - name: "=========== Remove the stopped container ==========="
      ansible.builtin.command: docker rm -f petstore-container-1
      ignore_errors: true

    - name: "=========== Remove the Docker images related to the container ==========="
      ansible.builtin.command: docker image prune -a --force
      ignore_errors: true

    - name: "=========== Build Docker Image ==========="
      ansible.builtin.command: docker build -t {{ ecr_app_name }}:v1 .  
      args:
        chdir: "{{ workspace }}"

    - name: "=========== Tag Petstore image ==========="
      ansible.builtin.command: docker tag petstore-image:v1 {{ ecr_repo_url }}/{{ ecr_app_name }}:v1 

