---
- name: "====================== Docker build and push ======================"
  hosts: webserver  # Replace with the hostname or IP address of your target server

  tasks:
    - name: "=========== Stop the container if it's running ==========="
      ansible.builtin.command: docker stop petstore-container-1
      ignore_errors: true

    - name: "=========== Remove the stopped container ==========="
      ansible.builtin.command: docker rm -f petstore-container-1
      ignore_errors: true

    - name: "=========== Remove the Docker images related to the container ==========="
      ansible.builtin.command: docker image prune -a --force
      ignore_errors: true

    - name: "=========== Copy project files to VM ==========="
      ansible.builtin.copy:
        src: "{{ workspace }}/"
        dest: /home/ubuntu/petstore/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: "=========== Build Docker Image ==========="
      ansible.builtin.command: docker build -t {{ ecr_app_name }}:v1 .  
      args:
        chdir: /home/ubuntu/petstore

    - name: "=========== Tag Petstore image ==========="
      ansible.builtin.command: docker tag petstore-image:v1 {{ ecr_repo_url }}/{{ ecr_app_name }}:v1 

